### ISSUE TITLE
ikea-tradfri-plugin Docker Synology importerror

### ISSUE THREAD

**Issue by Appiejs** [moroen/IKEA-Tradfri-plugin#76]
Hi there, I tried to install the plugin with docker on my Synology, but the plugin keeps restarting in docker with the following message:

Traceback (most recent call last):
File "tradfri.tac", line 21, in <module>
from ikeatradfri.device_classes import ikeaGroup, ikeaLight, ikeaSocket
ImportError: No module named 'ikeatradfri'

I noticed that the tradfri.tac file is modified 14 days ago, maybe it has to do something with the error?
If I could try and test something please let me know.
Gr
Ap

**Comment by moroen** [comment]
There was a COPY directive missing in the dockerfiles, the latest commit just pushed should fix this.

Regards,
M

**Comment by Appiejs** [comment]
HI thanks for the quick reply. What do I need to do to get the new file?

**Comment by moroen** [comment]
You need to pull the latest changes using git:

$ cd IKEA-Tradfri
$ git pull

**Comment by Appiejs** [comment]
probably i'm doing something wrong, but still getting the same error. I'm using de docker method on a Synology NAS and walked trough the process from start. After running the the container it's giving the same errors. What am I missing in the process?

**Comment by moroen** [comment]
I've build a image with the latest changes, and the adapter works. Have you rebuild the docker image without using the cache?

`
$ docker build --no-cache -t ikea-tradfri-plugin:latest .
`

**Comment by Appiejs** [comment]
Hi There,
i tried with the no-cache without any luck. Even the log has another message:
No module named 'ikeatradfri'
from ikeatradfri.device_classes import ikeaGroup, ikeaLight, ikeaSocket
File "tradfri.tac", line 21, in <module>
Traceback (most recent call last):
Please check IP/KEY.
Error: Connection to gateway timed out!

any idea

**Comment by moroen** [comment]
Are you sure you have the latest Dockerfile? Could you please post it here?

**Comment by Appiejs** [comment]
attached is the file from where i run the command, I think you mean this
file right?

Op di 28 mei 2019 om 15:05 schreef moroen <notifications@github.com>:

**Comment by moroen** [comment]
I'm not sure what has happened, but it looks like the latest changes somehow haven't been pushed to the repo. I've made the changes to the dockerfiles now, please pull the latest version and try again!

**Comment by Appiejs** [comment]
Hi, i see the new docker file, but now i'm back at the first issue.
de .tac file is still 18 days old, probably that file is also not synced?

**Comment by moroen** [comment]
The .tac file does't need changing, my on the fly correction of the dockerfiles were wrong. The versions available now, should work...

**Comment by Appiejs** [comment]
Perfect that fixed the issue, many thanks!
